[package]
name = "solana-bonding-curve-launchpad"
version = "0.1.0"
description = "High-performance Token-2022 Bonding Curve Launchpad on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "launchpad"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.30.1", features = ["token_2022"] }
solana-program = "=1.18.26"
spl-token-2022 = { version = "=0.11.0", features = ["no-entrypoint"] }
spl-token-metadata-interface = "=0.3.3"
spl-type-length-value = "=0.4.3"
bytemuck = "=1.16.0"
thiserror = "=1.0"
